# -*- coding: utf-8 -*-
"""VGG_16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IQgtZwN56NP7ieO1lR9O68jXxgyHFJ6P
"""

from tensorflow.keras.applications import VGG16
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input, decode_predictions
import numpy as np
import os

# Cargar el modelo pre-entrenado VGG-16
model = VGG16(weights='imagenet')

# Cargar y preprocesar una imagen
img_path = os.path.join(os.getcwd(), 'images', 'carro.png')  # Reemplaza con la ruta de la imagen
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

# Realizar la predicción
predictions = model.predict(x)
# Decodificar las predicciones
decoded_predictions = decode_predictions(predictions, top=3)[0]

# Mostrar los resultados
for i, (imagenet_id, label, score) in enumerate(decoded_predictions):
    print(f"{i+1}: {label} ({score:.2f})")